/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/users": {
    get: operations["usersGet"];
  };
}

export interface components {
  schemas: {
    "user-create": {
      /** Name of the user */
      name: string;
      /** Age of user */
      age: number;
    };
    "user-model": {
      id: number;
      createdAt: components["schemas"]["timestamp"];
      /** Users Role */
      role: "Student" | "Staff";
      /** Users First Name */
      first_name: string;
      /** Users Last Name */
      last_name?: string;
      /** Users Other Name */
      other_name?: string;
      /** Users Passport photo */
      profile_image?: string;
      email?: string;
      /** Users assigned Id */
      user_id?: number;
      /** Student's Passcode */
      password?: number;
      gender?: "male" | "female" | "other";
      phone?: string;
    } & components["schemas"]["user-create"];
    /** An ISO formatted timestamp */
    timestamp: Date | string;
    /** Student description */
    StudentDetails: {
      /** If Student, their programme */
      programme: string;
      /** Date Student Entered University */
      entry_date: string;
      hall?:
        | "Legon"
        | "Volta"
        | "Mensah Sarbah"
        | "Akuafo"
        | "Common Wealth"
        | "Dr. Hilla Liman"
        | "Alexander Kwapong"
        | "Elizabeth Frances Sey"
        | "Jean Nelson"
        | "Non-Resident";
      place_of_birth: string;
      region: string;
      guardian_or_kin: components["schemas"]["GuardianKin"];
      nationality: components["schemas"]["Nationality"];
      stages?: { [key: string]: components["schemas"]["Stage"] };
      medical?: components["schemas"]["Medical"];
      complaints?: { [key: string]: components["schemas"]["Complaint"] };
    };
    StaffDetails: {
      /** Not included in MVP */
      dept: { [key: string]: any };
    };
    Stage: {
      offering_type: "full-time" | "part-time";
      level: 100 | 200 | 300 | 400;
      /** Degree type student is pursing, eg, first is Bachelors */
      cycle: "first" | "second" | "third";
      semester: "first" | "second";
      courses: { [key: string]: components["schemas"]["Course"] };
    };
    Course: {
      name: string;
      credit: number;
      course_staff: { [key: string]: components["schemas"]["CourseStaff"] };
    };
    CourseStaff: {
      staff?: {
        role?: "lecturer" | "teaching_assistant";
        staff_id?: string;
      };
      /** Weeks the staff handled the course */
      time?: "full" | "partial";
      dates?: {
        start?: string;
        end?: string;
      };
      staff_id?: string;
    };
    GuardianKin: {
      /** Users First Name */
      first_name: string;
      /** Users Last Name */
      last_name: string;
      email?: string;
      phone: string;
    };
    Medical: {
      questions?: {
        history?: { [key: string]: components["schemas"]["MedicalHistory"] };
        dentals?: { [key: string]: components["schemas"]["DentalExamination"] };
        immunization?: {
          [key: string]: components["schemas"]["PastImmunization"];
        };
      };
      additional_info?: string;
    };
    MedicalHistory: {
      question: string;
      answer?: boolean;
    };
    DentalExamination: {
      question: string;
      answer?: { [key: string]: string };
    };
    PastImmunization: {
      question: string;
      date: string;
      answer?: boolean;
    };
    Complaint: {
      compliant_type: string;
      additional_info?: string;
    };
    Nationality:
      | "Afghanistan"
      | "Albania"
      | "Algeria"
      | "American Samoa"
      | "Andorra"
      | "Angola"
      | "Anguilla"
      | "Antarctica"
      | "Antigua and Barbuda"
      | "Argentina"
      | "Armenia"
      | "Aruba"
      | "Australia"
      | "Austria"
      | "Azerbaijan"
      | "Bahamas"
      | "Bahrain"
      | "Bangladesh"
      | "Barbados"
      | "Belarus"
      | "Belgium"
      | "Belize"
      | "Benin"
      | "Bermuda"
      | "Bhutan"
      | "Bolivia"
      | "Bosnia and Herzegovina"
      | "Botswana"
      | "Brazil"
      | "British Indian Ocean Territory"
      | "British Virgin Islands"
      | "Brunei"
      | "Bulgaria"
      | "Burkina Faso"
      | "Burundi"
      | "Cambodia"
      | "Cameroon"
      | "Canada"
      | "Cape Verde"
      | "Cayman Islands"
      | "Central African Republic"
      | "Chad"
      | "Chile"
      | "China"
      | "Christmas Island"
      | "Cocos Islands"
      | "Colombia"
      | "Comoros"
      | "Cook Islands"
      | "Costa Rica"
      | "Croatia"
      | "Cuba"
      | "Cyprus"
      | "Czech Republic"
      | "Democratic Republic of the Congo"
      | "Denmark"
      | "Djibouti"
      | "Dominica"
      | "Dominican Republic"
      | "East Timor"
      | "Ecuador"
      | "Egypt"
      | "El Salvador"
      | "Equatorial Guinea"
      | "Eritrea"
      | "Estonia"
      | "Ethiopia"
      | "Falkland Islands"
      | "Faroe Islands"
      | "Fiji"
      | "Finland"
      | "France"
      | "French Polynesia"
      | "Gabon"
      | "Gambia"
      | "Georgia"
      | "Germany"
      | "Ghana"
      | "Gibraltar"
      | "Greece"
      | "Greenland"
      | "Grenada"
      | "Guam"
      | "Guatemala"
      | "Guinea"
      | "Guinea-Bissau"
      | "Guyana"
      | "Haiti"
      | "Honduras"
      | "Hong Kong"
      | "Hungary"
      | "Iceland"
      | "India"
      | "Indonesia"
      | "Iran"
      | "Iraq"
      | "Ireland"
      | "Isle of Man"
      | "Israel"
      | "Italy"
      | "Ivory Coast"
      | "Jamaica"
      | "Japan"
      | "Jersey"
      | "Jordan"
      | "Kazakhstan"
      | "Kenya"
      | "Kiribati"
      | "Kuwait"
      | "Kyrgyzstan"
      | "Laos"
      | "Latvia"
      | "Lebanon"
      | "Lesotho"
      | "Liberia"
      | "Libya"
      | "Liechtenstein"
      | "Lithuania"
      | "Luxembourg"
      | "Macao"
      | "Macedonia"
      | "Madagascar"
      | "Malawi"
      | "Malaysia"
      | "Maldives"
      | "Mali"
      | "Malta"
      | "Marshall Islands"
      | "Mauritania"
      | "Mauritius"
      | "Mayotte"
      | "Mexico"
      | "Micronesia"
      | "Moldova"
      | "Monaco"
      | "Mongolia"
      | "Montenegro"
      | "Montserrat"
      | "Morocco"
      | "Mozambique"
      | "Myanmar"
      | "Namibia"
      | "Nauru"
      | "Nepal"
      | "Netherlands"
      | "Netherlands Antilles"
      | "New Caledonia"
      | "New Zealand"
      | "Nicaragua"
      | "Niger"
      | "Nigeria"
      | "Niue"
      | "North Korea"
      | "Northern Mariana Islands"
      | "Norway"
      | "Oman"
      | "Pakistan"
      | "Palau"
      | "Panama"
      | "Papua New Guinea"
      | "Paraguay"
      | "Peru"
      | "Philippines"
      | "Pitcairn"
      | "Poland"
      | "Portugal"
      | "Puerto Rico"
      | "Qatar"
      | "Republic of the Congo"
      | "Romania"
      | "Russia"
      | "Rwanda"
      | "Saint Barthelemy"
      | "Saint Helena"
      | "Saint Kitts and Nevis"
      | "Saint Lucia"
      | "Saint Martin"
      | "Saint Pierre and Miquelon"
      | "Saint Vincent and the Grenadines"
      | "Samoa"
      | "San Marino"
      | "Sao Tome and Principe"
      | "Saudi Arabia"
      | "Senegal"
      | "Serbia"
      | "Seychelles"
      | "Sierra Leone"
      | "Singapore"
      | "Slovakia"
      | "Slovenia"
      | "Solomon Islands"
      | "Somalia"
      | "South Africa"
      | "South Georgia and the South Sandwich Islands"
      | "South Korea"
      | "Spain"
      | "Sri Lanka"
      | "Sudan"
      | "Suriname"
      | "Svalbard and Jan Mayen"
      | "Swaziland"
      | "Sweden"
      | "Switzerland"
      | "Syria"
      | "Taiwan"
      | "Tajikistan"
      | "Tanzania"
      | "Thailand"
      | "Togo"
      | "Tokelau"
      | "Tonga"
      | "Trinidad and Tobago"
      | "Tunisia"
      | "Turkey"
      | "Turkmenistan"
      | "Turks and Caicos Islands"
      | "Tuvalu"
      | "U.S. Virgin Islands"
      | "Uganda"
      | "Ukraine"
      | "United Arab Emirates"
      | "United Kingdom"
      | "United States"
      | "Uruguay"
      | "Uzbekistan"
      | "Vanuatu"
      | "Vatican"
      | "Venezuela"
      | "Vietnam"
      | "Wallis and Futuna"
      | "Western Sahara"
      | "Yemen"
      | "Zambia"
      | "Zimbabwe";
  };
}

export interface operations {
  usersGet: {
    parameters: {
      query: {
        /** Search for users */
        q?: string | null;
        count?: number;
        page?: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            users: components["schemas"]["user-model"][];
          };
        };
      };
    };
  };
}

export interface external {}
